# Generated by Django 2.1.2 on 2018-10-10 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(unique=True, verbose_name='ID Пользователя')),
                ('client_add_num', models.IntegerField(verbose_name='Номер п/п')),
                ('client_name', models.CharField(max_length=256, verbose_name='Фамилия Имя Отчество')),
                ('client_email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('client_phone', models.CharField(default='', max_length=12, verbose_name='№ телефона')),
                ('client_phone_work', models.CharField(default='', max_length=12, verbose_name='№ телефона раб')),
                ('client_phone_other', models.CharField(default='', max_length=12, verbose_name='№ телефона доп')),
                ('client_birthday', models.DateField(verbose_name='Дата рождения')),
                ('client_passport', models.CharField(default='', max_length=20, verbose_name='Паспорт')),
                ('client_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='Status_client_Creditor',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(max_length=15, null=True, verbose_name='Статус по кредитору')),
            ],
            options={
                'verbose_name': 'Статус по кредитору',
                'verbose_name_plural': 'Статусы по кредитору',
            },
        ),
        migrations.CreateModel(
            name='Status_client_Info',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('status_name', models.CharField(max_length=15, null=True, verbose_name='Статус клиента')),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статус клиентов',
            },
        ),
        migrations.AddField(
            model_name='clients',
            name='client_status_creditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Status_client_Creditor'),
        ),
        migrations.AddField(
            model_name='clients',
            name='client_status_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Status_client_Info'),
        ),
    ]
