# Generated by Django 2.1.2 on 2018-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_client_creditor',
            name='status_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Статус по кредитору'),
        ),
        migrations.AlterField(
            model_name='status_client_info',
            name='status_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Статус клиента'),
        ),
    ]
