# Generated by Django 2.1.2 on 2018-10-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20181010_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit_Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Тип кредита')),
            ],
            options={
                'verbose_name': 'Тип кредита',
                'verbose_name_plural': 'Типы кредитов',
            },
        ),
    ]
