# Generated by Django 2.1.2 on 2018-10-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20181010_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_type',
            name='id',
            field=models.UUIDField(blank=True, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
