# Generated by Django 2.1.2 on 2018-10-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20181010_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_add_num',
            field=models.IntegerField(default='', null=True, verbose_name='Номер п/п'),
        ),
    ]
