# Generated by Django 2.1.2 on 2018-10-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20181010_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_phone',
            field=models.CharField(default=0, max_length=12, verbose_name='№ телефона'),
        ),
    ]
