# Generated by Django 2.1.2 on 2018-10-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20181010_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_add_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Номер п/п'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_phone',
            field=models.CharField(default='', max_length=12, verbose_name='№ телефона'),
        ),
    ]
