# Generated by Django 2.1.2 on 2018-10-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_auto_20181010_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status_client_creditor',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status_client_info',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
